---
title: "PlanetBayIndex"
author: "Logan"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tmap) 
library(mapview)
library(sf)
library(raster)
library(stringr)
library(questionr)
library(dplyr)
library(rgdal)
library(rgeos)
library(ggplot2)
library(MASS)
library(pscl)
library(visreg)
library(mlogit)
library(rstanarm)
library(loo)
library(bayesplot)
library(shinystan)
library(readxl)
library(reshape2)
library(data.table)
library(randomForest)
require(caTools)
library(tidycensus)
library(stargazer)
```

# Read in footprints and parcel info
```{r}
Footprints<-st_transform(st_zm(read_sf(
  "./Building Data/BuildingFootprints.shp")), 
  crs = 6440) # set CRS to Nad 83 , north Florida projection (m)

Parcels<-st_transform(st_zm(read_sf(
  "./Building Data/Parcels.shp")), 
  crs = 6440)
```

# Make Single Family Set
```{r}
Property<-st_join(Footprints,Parcels, left = TRUE, largest = TRUE) #join the parcel that shares the most areas with footprint
PropertySF<-subset(Property, DORAPPDESC=="SINGLE FAMILY")
```

# Extract Raster Values by Footprint

I firt define a function to 
```{r}
MosaicExtractRaster<-function(RasterLocation,UOA){ # 2 inputs - folder where rasters are stored and the unit of extraction (e.g. polygons, points)
  
  current.list <- list.files(path=paste(RasterLocation), full.names=TRUE, pattern = ".tif") 
  
  # read in raster files as a raster stack
  raster.list<- lapply(current.list, raster::stack) 
  
  # clear user defined names if present
  names(raster.list) <- NULL 
  
  # this tells the mosaic function to average any overlapping pixels
  raster.list$fun <- mean 
  
  # mosaic list using the mosaic function the raster package
  Mosaic <- do.call( raster::mosaic, raster.list)
  
  # match coordinate system of the mosaiced raster
  Mosaic<-projectRaster(Mosaic, crs = crs(UOA))
  
  # extract (join) raster values to points or polygons. 
  ex <- extract(Mosaic, 
                UOA, 
                fun=mean, #take the mean raster values (change to sum or other function if desired)
                na.rm=TRUE,
                df=TRUE)
  
  ex<-cbind(UOA,ex)
  
  return(ex)
}

#Make list of directories containing rasters by month
#current.dirs <- list.dirs("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryProject/PlanetData/Monthly",recursive = FALSE, full.names = TRUE)
  
#Extract average raster value by footprint-month
#PropertyRGB.list<- lapply(current.dirs, MosaicExtractRaster, UOA = PropertySF) #cant get this loop to work without crashing...


# Run function for each year of imagery. Save as object and export
RGBExt_10_2018<-st_write(select(MosaicExtractRaster(
                          "./PlanetData/Monthly/10_2018",PropertySF), # extract single family properties
                              GlobalID=GlobalID.y,
                              layer.1, #clean data to just the three extracted bands
                              layer.2,
                              layer.3),
                                 "./PlanetData/Monthly/10_2018/RGBExt_10_2018.shp") #export to avoid reanalysis

RGBExt_11_2018<-st_write(select(MosaicExtractRaster(
                          "./PlanetData/Monthly/11_2018",PropertySF),
                              GlobalID=GlobalID.y,
                              layer.1,
                              layer.2,
                              layer.3),
                                 "./PlanetData/Monthly/11_2018/RGBExt_11_2018.shp")
                         
RGBExt_12_2018<-st_write(select(MosaicExtractRaster(
                          "./PlanetData/Monthly/12_2018",PropertySF),
                              GlobalID=GlobalID.y,
                              layer.1,
                              layer.2,
                              layer.3),
                                 "./PlanetData/Monthly/12_2018/RGBExt_12_2018.shp")

RGBExt_01_2019<-st_write(select(MosaicExtractRaster(
                          "./PlanetData/Monthly/01_2019",PropertySF),
                              GlobalID=GlobalID.y,
                              layer.1,
                              layer.2,
                              layer.3),
                                 "./PlanetData/Monthly/01_2019/RGBExt_01_2019.shp")

RGBExt_02_2019<-st_write(select(MosaicExtractRaster(
                          "./PlanetData/Monthly/02_2019",PropertySF),
                              GlobalID=GlobalID.y,
                              layer.1,
                              layer.2,
                              layer.3),
                                 "./PlanetData/Monthly/02_2019/RGBExt_02_2019.shp")

RGBExt_03_2019<-st_write(select(MosaicExtractRaster(
                          "./PlanetData/Monthly/03_2019",PropertySF),
                              GlobalID=GlobalID.y,
                              layer.1,
                              layer.2,
                              layer.3),
                                 "./PlanetData/Monthly/03_2019/RGBExt_03_2019.shp")

RGBExt_04_2019<-st_write(select(MosaicExtractRaster(
                          "./PlanetData/Monthly/04_2019",PropertySF),
                              GlobalID=GlobalID.y,
                              layer.1,
                              layer.2,
                              layer.3),
                                 "./PlanetData/Monthly/04_2019/RGBExt_04_2019.shp")

RGBExt_05_2019<-st_write(select(MosaicExtractRaster(
                          "./PlanetData/Monthly/05_2019",PropertySF),
                              GlobalID=GlobalID.y,
                              layer.1,
                              layer.2,
                              layer.3),
                                 "./PlanetData/Monthly/05_2019/RGBExt_05_2019.shp")

RGBExt_06_2019<-st_write(select(MosaicExtractRaster(
                          "./PlanetData/Monthly/06_2019",PropertySF),
                              GlobalID=GlobalID.y,
                              layer.1,
                              layer.2,
                              layer.3),
                                 "./PlanetData/Monthly/06_2019/RGBExt_06_2019.shp")

RGBExt_07_2019<-st_write(select(MosaicExtractRaster(
                          "./PlanetData/Monthly/07_2019",PropertySF),
                              GlobalID=GlobalID.y,
                              layer.1,
                              layer.2,
                              layer.3),
                                 "./PlanetData/Monthly/07_2019/RGBExt_07_2019.shp")

RGBExt_08_2019<-st_write(select(MosaicExtractRaster(
                          "./PlanetData/Monthly/08_2019",PropertySF),
                              GlobalID=GlobalID.y,
                              layer.1,
                              layer.2,
                              layer.3),
                                 "./PlanetData/Monthly/08_2019/RGBExt_08_2019.shp")

RGBExt_09_2019<-st_write(select(MosaicExtractRaster(
                          "./PlanetData/Monthly/09_2019",PropertySF),
                              GlobalID=GlobalID.y,
                              layer.1,
                              layer.2,
                              layer.3),
                                 "./PlanetData/Monthly/09_2019/RGBExt_09_2019.shp")

RGBExt_10_2019<-st_write(select(MosaicExtractRaster(
                          "./PlanetData/Monthly/10_2019",PropertySF),
                              GlobalID=GlobalID.y,
                              layer.1,
                              layer.2,
                              layer.3),
                                 "./PlanetData/Monthly/10_2019/RGBExt_10_2019.shp")

```

# Reduce to Prediction Set


# Predict Tarp Status
```{r}
PropertyRGBN10.Modeled <- predict(rf, newdata=PropertyRGBN10.ToModel)
PropertyRGBN11.Modeled <- predict(rf, newdata=PropertyRGBN11.ToModel)
PropertyRGBN12.Modeled <- predict(rf, newdata=PropertyRGBN12.ToModel)

PropertSF$Tarp10<-PropertyRGBN10.Modeled
PropertSF$Tarp11<-PropertyRGBN11.Modeled
PropertSF$Tarp12<-PropertyRGBN12.Modeled

```

# Make Cover Month
```{r}
PropertSF$CoverSum<-as.numeric(PropertSF$Tarp10) + as.numeric(PropertSF$Tarp11) + as.numeric(PropertSF$Tarp12)

PropertSF$CoverMonth<-ifelse(PropertSF$Tarp10 == "1",  0,
                             ifelse(PropertSF$Tarp10 == "0" & PropertSF$Tarp11 =="1",1,
                                    ifelse(PropertSF$Tarp10 == "0" & PropertSF$Tarp11 =="0" & PropertSF$Tarp12 =="1",2,NA)))



PropertSF$ValSize<- ifelse(PropertSF$VAPTOTAL < median(PropertSF$VAPTOTAL) & PropertSF$S1AREATTL < median(PropertSF$S1AREATTL),"Cheap-Small",
                           ifelse(PropertSF$VAPTOTAL < median(PropertSF$VAPTOTAL) & PropertSF$S1AREATTL >= median(PropertSF$S1AREATTL),"Cheap-Large",
                                  ifelse(PropertSF$VAPTOTAL >= median(PropertSF$VAPTOTAL) & PropertSF$S1AREATTL < median(PropertSF$S1AREATTL),"Expensive-Small",
                                          ifelse(PropertSF$VAPTOTAL >= median(PropertSF$VAPTOTAL) & PropertSF$S1AREATTL >= median(PropertSF$S1AREATTL),"Expensive-Large",0))))


PropertSF$LargeSmall<-ifelse(PropertSF$ValSize == "Cheap-Large", "Large",
                             ifelse(PropertSF$ValSize == "Expensive-Large", "Large","Small"))


PropertSF$ExpCheap<-ifelse(PropertSF$ValSize == "Expensive-Small", "Expensive",
                             ifelse(PropertSF$ValSize == "Expensive-Large", "Expensive","Cheap"))

PropertSF<-subset(PropertSF,
                                                     VAPBLDG>50000&
                                                     VAPBLDG<10000000&
                                                     S1AREATTL>500&
                                                     S1AREATTL<15000)



PropertSF$DolSQF<- na.rm(PropertSF$VAPTOTAL / PropertSF$S1AREATTL)

PropertSF$DolSQFLAble <- ifelse(PropertSF$DolSQF < median(PropertSF$DolSQF),"Less Valuable", "More Valuable")


table(PropertSF$DolSQFLAble)

summary(PropertSF$DolSQF)

                          
```

Download Census Tracts
```{r}
Zip_2010 <- get_decennial( #download 2010 tracts from Census API
      state = "FL",
      geography = "zcta",
      variables = "P001001",
      output = "wide",
    # survey = "sf1",
      year = 2010,
      geometry = TRUE
      )



```

```{r}
Michael<-read_sf("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@Response/Data/WindVectors/Michael_ATL_2018_1minMaxSus_OT_FtptSwath_BandedShp_12Oct_0600UTC_v1_Hwind_A_1.shp")
Michael<-st_transform(Michael, crs = 3857)

```


```{r}
ExternalityData<-read.csv("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@Externalities/Data and Code/Data Compilation/RegdataSF.csv")

Dist<-select(ExternalityData, GlobalID, UrbanDistance, CoastDist)

Dist$DistID<-Dist$GlobalID

```

Joins
```{r}
PropertSF<-st_transform(PropertSF, crs = 3857)
Zip_2010<-st_transform(Zip_2010, crs = 3857)

PropertSF<-st_join(PropertSF, Zip_2010, left = TRUE, largest = TRUE)
PropertSF<-st_join(PropertSF, Michael, left = TRUE, largest = TRUE)

PropertSF<-left_join(PropertSF, Dist, by=c("GlobalID.x" = "DistID"))

summary(PropertSF$UrbanDistance.y)

```


```{r}
test1<-glm(CoverMonth ~ ValSize +  GEOID , family="poisson", data= PropertSF)

test2<-lm(CoverMonth ~ ValSize + X1mSWmphBnd, data= PropertSF)

summary(test1)
summary(test2)
PropertSF$
```

```{r}

stargazer(test1, out = "html")
```


```{r}
library(gplots)

Plot<- plotmeans((CoverMonth)~ ValSize, data = subset(PropertSF,
                                                     VAPBLDG>50000&
                                                     VAPBLDG<10000000&
                                                     S1AREATTL>500&
                                                     S1AREATTL<15000), 
          frame = FALSE, 
          mean.labels = FALSE, 
          connect = FALSE,
          xlab = "Housing Catagory",
          ylab = "Service time (Months)")


Plot<- plotmeans((CoverMonth)~ DolSQFLAble, data = PropertSF,

          frame = FALSE, 
          mean.labels = FALSE, 
          connect = FALSE,
          xlab = "Housing Catagory",
          ylab = "Service time (Months)")




AreaPlot<-plotmeans(S1AREATTL~ CoverMonth, data = subset(PropertSF,
                                                     VAPBLDG>50000&
                                                     VAPBLDG<10000000&
                                                     S1AREATTL>500&
                                                     S1AREATTL<15000), 
          frame = FALSE, 
          mean.labels = FALSE, 
          connect = FALSE,
          xlab = "Months Elapsed",
          ylab = "Home Size (sq.ft.)")



ValPlot<-plotmeans(VAPTOTAL~ CoverMonth, data = subset(PropertSF,
                                                     VAPBLDG>50000&
                                                     VAPBLDG<10000000&
                                                     S1AREATTL>500&
                                                     S1AREATTL<15000), 
          frame = FALSE, 
          mean.labels = FALSE, 
          connect = FALSE,
          xlab = "Months Elapsed",
          ylab = "Assesed Value")
```











