---
title: "PlanetBayIndex"
author: "Logan"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tmap) 
library(mapview)
library(sf)
library(raster)
library(stringr)
library(questionr)
library(dplyr)
library(rgdal)
library(rgeos)
library(ggplot2)
library(MASS)
library(pscl)
library(visreg)
library(mlogit)
library(rstanarm)
library(loo)
library(bayesplot)
library(shinystan)
library(readxl)
library(reshape2)
library(data.table)
library(randomForest)
require(caTools)
library(tidycensus)
library(stargazer)
```



# Read in footprints and parcel info
```{r}
Footprints<-st_zm(read_sf("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryIndex/Building Data/BuildingFootprints.shp"))
Parcels<-st_zm(read_sf("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryIndex/Building Data/Parcels.shp"))
```

# Make Single Family Set
```{r}
Property<-st_join(Footprints,Parcels, left = TRUE, largest = TRUE) #join the parcel that shares the most areas with footprint
PropertSF<-subset(Property, DORAPPDESC=="SINGLE FAMILY")

```

# Extract Raster Values by footprint 
```{r}
PropertyRGBN10.28_30<-ExtractRaster("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryIndex/PlanetData/Daily/10_18-10_21",PropertSF)

PropertyRGBN10.<-ExtractRaster("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryIndex/PlanetData/Monthly/10_2018",PropertSF)
PropertyRGBN11.<-ExtractRaster("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryIndex/PlanetData/Monthly/11_2018",PropertSF)
PropertyRGBN12.<-ExtractRaster("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryIndex/PlanetData/Monthly/12_2018",PropertSF)
```

# Make Prediction Set
```{r}
PropertyRGBN10.ToModel<-select(PropertyRGBN10.,
                           GlobalID=GlobalID.y,
                           layer.1,
                           layer.2,
                           layer.3)

PropertyRGBN11.ToModel<-select(PropertyRGBN11.,
                           GlobalID=GlobalID.y,
                           layer.1,
                           layer.2,
                           layer.3)

PropertyRGBN12.ToModel<-select(PropertyRGBN12.,
                           GlobalID=GlobalID.y,
                           layer.1,
                           layer.2,
                           layer.3)
```

# Predict Tarp Status
```{r}
PropertyRGBN10.Modeled <- predict(rf, newdata=PropertyRGBN10.ToModel)
PropertyRGBN11.Modeled <- predict(rf, newdata=PropertyRGBN11.ToModel)
PropertyRGBN12.Modeled <- predict(rf, newdata=PropertyRGBN12.ToModel)

PropertSF$Tarp10<-PropertyRGBN10.Modeled
PropertSF$Tarp11<-PropertyRGBN11.Modeled
PropertSF$Tarp12<-PropertyRGBN12.Modeled

```

# Make Cover Month
```{r}
PropertSF$CoverSum<-as.numeric(PropertSF$Tarp10) + as.numeric(PropertSF$Tarp11) + as.numeric(PropertSF$Tarp12)

PropertSF$CoverMonth<-ifelse(PropertSF$Tarp10 == "1",  0,
                             ifelse(PropertSF$Tarp10 == "0" & PropertSF$Tarp11 =="1",1,
                                    ifelse(PropertSF$Tarp10 == "0" & PropertSF$Tarp11 =="0" & PropertSF$Tarp12 =="1",2,NA)))



PropertSF$ValSize<- ifelse(PropertSF$VAPTOTAL < median(PropertSF$VAPTOTAL) & PropertSF$S1AREATTL < median(PropertSF$S1AREATTL),"Cheap-Small",
                           ifelse(PropertSF$VAPTOTAL < median(PropertSF$VAPTOTAL) & PropertSF$S1AREATTL >= median(PropertSF$S1AREATTL),"Cheap-Large",
                                  ifelse(PropertSF$VAPTOTAL >= median(PropertSF$VAPTOTAL) & PropertSF$S1AREATTL < median(PropertSF$S1AREATTL),"Expensive-Small",
                                          ifelse(PropertSF$VAPTOTAL >= median(PropertSF$VAPTOTAL) & PropertSF$S1AREATTL >= median(PropertSF$S1AREATTL),"Expensive-Large",0))))


PropertSF$LargeSmall<-ifelse(PropertSF$ValSize == "Cheap-Large", "Large",
                             ifelse(PropertSF$ValSize == "Expensive-Large", "Large","Small"))


PropertSF$ExpCheap<-ifelse(PropertSF$ValSize == "Expensive-Small", "Expensive",
                             ifelse(PropertSF$ValSize == "Expensive-Large", "Expensive","Cheap"))

PropertSF<-subset(PropertSF,
                                                     VAPBLDG>50000&
                                                     VAPBLDG<10000000&
                                                     S1AREATTL>500&
                                                     S1AREATTL<15000)



PropertSF$DolSQF<- na.rm(PropertSF$VAPTOTAL / PropertSF$S1AREATTL)

PropertSF$DolSQFLAble <- ifelse(PropertSF$DolSQF < median(PropertSF$DolSQF),"Less Valuable", "More Valuable")


table(PropertSF$DolSQFLAble)

summary(PropertSF$DolSQF)

                          
```

Download Census Tracts
```{r}
Zip_2010 <- get_decennial( #download 2010 tracts from Census API
      state = "FL",
      geography = "zcta",
      variables = "P001001",
      output = "wide",
    # survey = "sf1",
      year = 2010,
      geometry = TRUE
      )



```

```{r}
Michael<-read_sf("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@Response/Data/WindVectors/Michael_ATL_2018_1minMaxSus_OT_FtptSwath_BandedShp_12Oct_0600UTC_v1_Hwind_A_1.shp")
Michael<-st_transform(Michael, crs = 3857)

```


```{r}
ExternalityData<-read.csv("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@Externalities/Data and Code/Data Compilation/RegdataSF.csv")

Dist<-select(ExternalityData, GlobalID, UrbanDistance, CoastDist)

Dist$DistID<-Dist$GlobalID

```

Joins
```{r}
PropertSF<-st_transform(PropertSF, crs = 3857)
Zip_2010<-st_transform(Zip_2010, crs = 3857)

PropertSF<-st_join(PropertSF, Zip_2010, left = TRUE, largest = TRUE)
PropertSF<-st_join(PropertSF, Michael, left = TRUE, largest = TRUE)

PropertSF<-left_join(PropertSF, Dist, by=c("GlobalID.x" = "DistID"))

summary(PropertSF$UrbanDistance.y)

```


```{r}
test1<-glm(CoverMonth ~ ValSize +  GEOID , family="poisson", data= PropertSF)

test2<-lm(CoverMonth ~ ValSize + X1mSWmphBnd, data= PropertSF)

summary(test1)
summary(test2)
PropertSF$
```

```{r}

stargazer(test1, out = "html")
```


```{r}
library(gplots)

Plot<- plotmeans((CoverMonth)~ ValSize, data = subset(PropertSF,
                                                     VAPBLDG>50000&
                                                     VAPBLDG<10000000&
                                                     S1AREATTL>500&
                                                     S1AREATTL<15000), 
          frame = FALSE, 
          mean.labels = FALSE, 
          connect = FALSE,
          xlab = "Housing Catagory",
          ylab = "Service time (Months)")


Plot<- plotmeans((CoverMonth)~ DolSQFLAble, data = PropertSF,

          frame = FALSE, 
          mean.labels = FALSE, 
          connect = FALSE,
          xlab = "Housing Catagory",
          ylab = "Service time (Months)")




AreaPlot<-plotmeans(S1AREATTL~ CoverMonth, data = subset(PropertSF,
                                                     VAPBLDG>50000&
                                                     VAPBLDG<10000000&
                                                     S1AREATTL>500&
                                                     S1AREATTL<15000), 
          frame = FALSE, 
          mean.labels = FALSE, 
          connect = FALSE,
          xlab = "Months Elapsed",
          ylab = "Home Size (sq.ft.)")



ValPlot<-plotmeans(VAPTOTAL~ CoverMonth, data = subset(PropertSF,
                                                     VAPBLDG>50000&
                                                     VAPBLDG<10000000&
                                                     S1AREATTL>500&
                                                     S1AREATTL<15000), 
          frame = FALSE, 
          mean.labels = FALSE, 
          connect = FALSE,
          xlab = "Months Elapsed",
          ylab = "Assesed Value")
```











