---
title: "PlanetBayIndex"
author: "Logan"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tmap) 
library(mapview)
library(sf)
library(raster)
library(stringr)
library(questionr)
library(dplyr)
library(rgdal)
library(rgeos)
library(ggplot2)
library(MASS)
library(pscl)
library(visreg)
library(mlogit)
library(rstanarm)
library(loo)
library(bayesplot)
library(shinystan)
library(readxl)
library(reshape2)
library(data.table)
library(randomForest)
require(caTools)
```


# Functions
```{r}
ExtractRaster<-function(RasterLocation,UOA){ 
 
  # make list of file names that are rasters. Note to change the pattern argument if rasters are not .tif. Alternatively you can remove the pattern argument if the file location only stores relevant raster files to be mosaiced. 
  current.list <- list.files(path=paste(RasterLocation), full.names=TRUE, pattern = ".tif") 
    
  # read in raster files as a raster stack
  raster.list<- lapply(current.list, stack) 
  
  # clear user defined names if present
  names(raster.list) <- NULL 
  
  # this tells the mosaic function to average any overlapping pixels
  raster.list$fun <- mean 
  
  # mosaic list using the mosaic function the raster package
  Mosaic <- do.call(mosaic, raster.list)
  
  # ensure joining units have a coordinate system
  UOA<-st_transform(UOA, crs = 3857)
  
  # match coordinate system of the mosaiced raster
  Mosaic<-projectRaster(Mosaic, crs = crs(UOA))

  # extract (join) raster values to points or polygons. 
  ex <- extract(Mosaic, 
    UOA, 
    fun=mean, #If polygons, take the mean raster values (change to sum or other function if desired)
    na.rm=TRUE,
    df=TRUE)

ex<-cbind(UOA,ex)

return(ex)
}
```

### Load Data
```{r}
FootprintsTarp<-st_zm(read_sf("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryIndex/TrainingData/TarpMaster.shp"))
FootprintsRoof<-st_zm(read_sf("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryIndex/TrainingData/RoofMaster.shp"))

```

### Extract Raster values by footprint
```{r}
FootprintsTarpRGBN<-ExtractRaster("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryIndex/PlanetData/Monthly/01_2019",FootprintsTarp)
FootprintsRoofRGBN<-ExtractRaster("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryIndex/PlanetData/Monthly/01_2019",FootprintsRoof)
```

### Compile Training set 
```{r}
#Subset
FootprintsTarpRGBN<-select(FootprintsTarpRGBN,
                           GlobalID,
                           layer.1,
                           layer.2,
                           layer.3)

FootprintsRoofRGBN<-select(FootprintsRoofRGBN,
                           GlobalID,
                           layer.1,
                           layer.2,
                           layer.3)

#Label Outcomes
FootprintsTarpRGBN$Tarp<-as.factor(1) 
FootprintsRoofRGBN$Tarp<-as.factor(0)


#stack
TrainingDat<-rbind(FootprintsTarpRGBN,FootprintsRoofRGBN)
TrainingDat<-st_drop_geometry(TrainingDat) #Drop geometry


#Split
sample = sample.split(TrainingDat$Tarp, SplitRatio = .75)
train = subset(TrainingDat, sample == TRUE)
test  = subset(TrainingDat, sample == FALSE)

```

# Models
```{r}
GLM_RB1<-glm(Tarp~layer.1+layer.3,family = binomial(link="logit"),data =TrainingDat)

hitmiss(GLM_RB1)

```

# Random Forest Estimator
```{r}
rf <- randomForest(Tarp ~ .,data=train)
rf#Show results within training set
```
# Random Forest Out of sample error
```{r}
pred = predict(rf, newdata=test[-5])
cm = table(test[,5], pred)
cm #Show results out of sample
```

# Save Random Forest
```{r}
saveRDS(rf, "BayPlanetRF.rds")
```



















```{r}
tmap_mode("view") #interactive
#tmap_mode("plot") #static

tm_shape(TrainTarp) + 
    tm_polygons("layer.1")

```





