---
title: "PlanetBayIndex"
author: "Logan"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tmap) 
library(mapview)
library(sf)
library(raster)
library(stringr)
library(questionr)
library(dplyr)
library(rgdal)
library(rgeos)
library(ggplot2)
library(MASS)
library(pscl)
library(visreg)
library(mlogit)
library(rstanarm)
library(loo)
library(bayesplot)
library(shinystan)
library(readxl)
library(reshape2)
library(data.table)
library(randomForest)
require(caTools)
```

# Load Data

### Training Footprints
```{r}
FootprintsTarp<-st_zm(read_sf("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryProject/TrainingData/TarpMaster.shp"))
FootprintsRoof<-st_zm(read_sf("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryProject/TrainingData/RoofMaster.shp"))

```

### Extract Raster values by footprint
```{r}
MosaicExtractRaster<-function(RasterLocation,UOA){ # 2 inputs - folder where rasters are stored and the unit of extraction (e.g. polygons, points)
  
  current.list <- list.files(path=paste(RasterLocation), full.names=TRUE, pattern = ".tif") 
  
  # read in raster files as a raster stack
  raster.list<- lapply(current.list, raster::stack) 
  
  # clear user defined names if present
  names(raster.list) <- NULL 
  
  # this tells the mosaic function to average any overlapping pixels
  raster.list$fun <- mean 
  
  # mosaic list using the mosaic function the raster package
  Mosaic <- do.call( raster::mosaic, raster.list)
  
  # match coordinate system of the mosaiced raster
  Mosaic<-projectRaster(Mosaic, crs = crs(UOA))
  
  # extract (join) raster values to points or polygons. 
  ex <- extract(Mosaic, 
                UOA, 
                fun=mean, #take the mean raster values (change to sum or other function if desired)
                na.rm=TRUE,
                df=TRUE)
  
  ex<-cbind(UOA,ex)
  
  return(ex)
}

FootprintsTarpRGB<-MosaicExtractRaster("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryProject/PlanetData/Monthly/01_2019",FootprintsTarp)

FootprintsRoofRGB<-MosaicExtractRaster("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryProject/PlanetData/Monthly/01_2019",FootprintsRoof)
```

### Compile Training set 
```{r}
#Subset
FootprintsTarpRGB<-select(FootprintsTarpRGB,
                           GlobalID,
                           layer.1,
                           layer.2,
                           layer.3)

FootprintsRoofRGB<-select(FootprintsRoofRGB,
                           GlobalID,
                           layer.1,
                           layer.2,
                           layer.3)

#Label Outcomes
FootprintsTarpRGB$TarpRoof<-as.factor("tarp")
FootprintsRoofRGB$TarpRoof<-as.factor("roof")


#stack
TrainingDatTarp<-st_drop_geometry(FootprintsTarpRGB) #Drop geometry
TrainingDatRoof<-st_drop_geometry(FootprintsRoofRGB)

TrainingDat<-rbind(TrainingDatTarp,TrainingDatRoof)


#Split
sample <- sample.split(TrainingDat$Tarp, SplitRatio = .75)
train <- subset(TrainingDat, sample == TRUE)
test  <- subset(TrainingDat, sample == FALSE)

```

# Models
```{r}
GLM_RB1_Monthly<-glm(TarpRoof~layer.1+layer.3,family = binomial(link="logit"),data =TrainingDat)

hitmiss(GLM_RB1_Monthly)

```

# Random Forest Estimator
```{r}
rfMonthly <- randomForest(TarpRoof ~ layer.1 + layer.2+ layer.3 ,data=TrainingDat)
rfMonthly#Show results within training set
```
# Random Forest Out of sample error
```{r}
pred = predict(rfMonthly, newdata=test[-5])
cm = table(test[,5], pred)
cm #Show results out of sample
```

# Save Random Forest
```{r}
saveRDS(rfMonthly, "BayRFMonth.rds")
saveRDS(GLM_RB1_Monthly, "BayLogitMonth.rds")
```








