---
title: "PlanetBayIndex"
author: "Logan"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tmap) 
library(mapview)
library(sf)
library(raster)
library(stringr)
library(questionr)
library(dplyr)
library(rgdal)
library(rgeos)
library(ggplot2)
library(MASS)
library(pscl)
library(visreg)
library(mlogit)
library(rstanarm)
library(loo)
library(bayesplot)
library(shinystan)
library(readxl)
library(reshape2)
library(data.table)
library(randomForest)
require(caTools)
```

### Load Data
```{r}
FootprintsTarp<-st_zm(read_sf("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryProject/TrainingData/TarpMaster.shp"))
FootprintsRoof<-st_zm(read_sf("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryProject/TrainingData/RoofMaster.shp"))

```

### Extract Raster values by footprint
```{r}
FootprintsTarpRGB<-MosaicExtractRaster("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryProject/PlanetData/Monthly/01_2019",FootprintsTarp)

FootprintsRoofRGB<-MosaicExtractRaster("C:/Users/blair/OneDrive/Desktop/PhD/Dissertation/@TemporaryRoofandRecoveryProject/PlanetData/Monthly/01_2019",FootprintsRoof)
```

### Compile Training set 
```{r}
#Subset
FootprintsTarpRGB<-select(FootprintsTarpRGB,
                           GlobalID,
                           layer.1,
                           layer.2,
                           layer.3)

FootprintsRoofRGB<-select(FootprintsRoofRGB,
                           GlobalID,
                           layer.1,
                           layer.2,
                           layer.3)

#Label Outcomes
FootprintsTarpRGB$Tarp<-as.factor(1) 
FootprintsRoofRGB$Tarp<-as.factor(0)


#stack
TrainingDat<-rbind(FootprintsTarpRGB,FootprintsRoofRGB)
TrainingDat<-st_drop_geometry(TrainingDat) #Drop geometry


#Split
sample <- sample.split(TrainingDat$Tarp, SplitRatio = .75)
train <- subset(TrainingDat, sample == TRUE)
test  <- subset(TrainingDat, sample == FALSE)

```

# Models
```{r}
GLM_RB1<-glm(Tarp~layer.1+layer.3,family = binomial(link="logit"),data =TrainingDat)

hitmiss(GLM_RB1)

```

# Random Forest Estimator
```{r}
rf <- randomForest(Tarp ~ .,data=train)
rf#Show results within training set
```
# Random Forest Out of sample error
```{r}
pred = predict(rf, newdata=test[-5])
cm = table(test[,5], pred)
cm #Show results out of sample
```

# Save Random Forest
```{r}
saveRDS(rf, "BayPlanetRF.rds")
```


```{r}
tmap_mode("view") #interactive
#tmap_mode("plot") #static

tm_shape(TrainTarp) + 
    tm_polygons("layer.1")

```









